# Generated by Django 5.0.6 on 2024-07-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petanddogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
