# Generated by Django 5.0.6 on 2024-07-08 02:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petanddogs', '0002_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Compra')),
                ('estado_pedido', models.CharField(default='recibido', max_length=20, verbose_name='Estado del Pedido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='petanddogs.boletacompra', verbose_name='Boleta de Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petanddogs.producto', verbose_name='Producto')),
            ],
        ),
    ]
